// apps/web/src/features/globe/PhotoPin.tsx
import React from 'react'
import { AudioLines, Image as ImageIcon, Video } from 'lucide-react'
import { useAudioPlayer } from '../media/AudioContext.js'
import { translate, formatLocation } from '../../i18n/i18n.js'
import type { OccurrenceRecord } from '@gbif-globe/contracts'
import { imageDisplayUrl } from '@gbif-globe/media'
import { PinImage } from './PinImage.js'

interface PhotoPinProps {
  record: OccurrenceRecord
  selected?: boolean
  language?: string
  showPhoto?: boolean
  onSelect?: (record: OccurrenceRecord) => void
  onHoverStart?: (record: OccurrenceRecord) => void
  onHoverEnd?: () => void
}

export function PhotoPin({
  record,
  selected = false,
  language = 'en',
  showPhoto = true,
  onSelect,
  onHoverStart,
  onHoverEnd,
}: PhotoPinProps) {
  const { currentTrack, isPlaying, activeSource } = useAudioPlayer()

  const isCurrentPlaying =
    activeSource === 'occurrence' &&
    isPlaying &&
    String(currentTrack?.gbifID) === String(record.gbifId)

  const mediaKinds = new Set(record.media.map(m => m.kind))
  const thumbnailUrl = showPhoto ? imageDisplayUrl(record.media.find(m => m.kind === 'image'), 'pin') : ''
  const location = formatLocation(record, language)
  const taxonClass = record.class?.toLowerCase() || 'other'

  return (
    <div className="photo-pin-container">
      <button
        className={`photo-pin photo-pin--single ${selected ? 'is-selected' : ''} ${isCurrentPlaying ? 'is-playing-audio' : ''}`}
        type="button"
        aria-label={translate(language, 'marker.named', { name: record.scientificName })}
        onMouseEnter={() => onHoverStart?.(record)}
        onMouseLeave={onHoverEnd}
        onClick={e => {
          e.stopPropagation()
          onSelect?.(record)
        }}
      >
        {isCurrentPlaying && (
          <>
            <span className="photo-pin__sound-wave wave-1" />
            <span className="photo-pin__sound-wave wave-2" />
            <span className="photo-pin__sound-wave wave-3" />
            <span className="photo-pin__beacon" aria-hidden="true">
              <span className="beacon-bar bar-1" />
              <span className="beacon-bar bar-2" />
              <span className="beacon-bar bar-3" />
            </span>
          </>
        )}

        <span className="photo-pin__pulse" />
        <span className="photo-pin__ping" />
        <span className={`photo-pin__image taxon-${taxonClass}`}>
          {thumbnailUrl && <PinImage src={thumbnailUrl} alt={record.scientificName} />}
        </span>

        <span className="photo-pin__inner">
          {!thumbnailUrl && mediaKinds.has('audio') ? (
            <AudioLines size={18} />
          ) : !thumbnailUrl && mediaKinds.has('video') ? (
            <Video size={18} />
          ) : (
            !thumbnailUrl && <ImageIcon size={18} />
          )}
        </span>
      </button>

      <div className="pin-tooltip" role="tooltip">
        <strong>{record.vernacularName || record.scientificName}</strong>
        <span>{location}</span>
      </div>
    </div>
  )
}

// src/components/PhotoPin.vue
<script setup>
import { computed, toRef } from 'vue'
import { Image as ImageIcon } from '@lucide/vue'
import { useOccurrenceMedia } from '../composables/useOccurrenceMedia.js'
import { formatLocation } from '../map/formatting.js'
import { translate } from '../i18n.js'
import MapMarker from './MapMarker.vue'

const props = defineProps({
  record: { type: Object, required: true },
  selected: { type: Boolean, default: false },
  language: { type: String, default: 'en' },
})

const emit = defineEmits(['select', 'hover-start', 'hover-end'])
const recordRef = toRef(props, 'record')
const { thumbnailUrl } = useOccurrenceMedia(recordRef)
const location = computed(() => formatLocation(props.record, props.language))
</script>

<template>
  <MapMarker :lng-lat="[record.longitude, record.latitude]">
    <button
      class="photo-pin photo-pin--single"
      :class="{ 'is-selected': selected }"
      type="button"
      :aria-label="translate(language, 'marker.named', { name: record.scientificName })"
      @mouseenter="emit('hover-start', record)"
      @mouseleave="emit('hover-end')"
      @click.stop="emit('select', record)"
    >
      <span class="photo-pin__pulse" />
      <span class="photo-pin__ping" />
      <span class="photo-pin__image" :class="`taxon-${record.class?.toLowerCase() || 'other'}`">
        <img v-if="thumbnailUrl" :src="thumbnailUrl" :alt="record.scientificName" />
        <ImageIcon v-if="selected || !thumbnailUrl" :size="18" />
      </span>
    </button>
    <div class="pin-tooltip" role="tooltip">
      <strong>{{ record.scientificName }}</strong>
      <span>{{ location }}</span>
    </div>
  </MapMarker>
</template>
