// frontend/src/components/MapControls.vue
<script setup>
import { Focus, House, Languages, Minus, Monitor, Plus, SlidersVertical, Waves } from '@lucide/vue'
import { translate } from '../i18n.js'

const props = defineProps({
  filterOpen: { type: Boolean, default: false },
  ambientSoundActive: { type: Boolean, default: false },
  theme: { type: String, default: 'dark' },
  language: { type: String, default: 'en' },
})

defineEmits(['home', 'toggle-ambient-sound', 'toggle-filter', 'toggle-theme', 'toggle-language', 'zoom-in', 'zoom-out', 'reset-bearing'])

const label = key => translate(props.language, key)
</script>

<template>
  <div class="control-top-left">
    <button class="glass-control" type="button" :aria-label="label('controls.home')" @click="$emit('home')">
      <House :size="20" />
    </button>
  </div>

  <div class="control-top-right">
    <button class="glass-control" :class="{ active: filterOpen }" type="button" :aria-label="label('controls.filter')" @click="$emit('toggle-filter')">
      <SlidersVertical :size="20" />
    </button>
    <button class="glass-control" type="button" :aria-label="label(theme === 'dark' ? 'controls.useLight' : 'controls.useDark')" @click="$emit('toggle-theme')">
      <Monitor :size="20" />
    </button>
    <button class="glass-control control-language" type="button" :aria-label="label(language === 'zh' ? 'controls.switchToEnglish' : 'controls.switchToChinese')" @click="$emit('toggle-language')">
      <Languages :size="18" />
      <span aria-hidden="true">{{ language === 'zh' ? 'EN' : '中' }}</span>
    </button>
    <button class="glass-control" :class="{ active: ambientSoundActive }" type="button" :aria-label="label('controls.ambientSound')" @click="$emit('toggle-ambient-sound')">
      <Waves :size="20" />
    </button>
  </div>

  <div class="control-zoom">
    <button type="button" :aria-label="label('controls.zoomIn')" @click="$emit('zoom-in')"><Plus :size="21" /></button>
    <button type="button" :aria-label="label('controls.zoomOut')" @click="$emit('zoom-out')"><Minus :size="21" /></button>
    <button type="button" :aria-label="label('controls.bearing')" @click="$emit('reset-bearing')"><Focus :size="20" /></button>
  </div>
</template>

// apps/web/src/features/globe/MapControls.tsx
import React from 'react'
import { Focus, House, Languages, Minus, Monitor, Plus, SlidersVertical, Waves } from 'lucide-react'
import { translate } from '../../i18n/i18n.js'

interface MapControlsProps {
  filterOpen: boolean
  ambientSoundActive: boolean
  theme: string
  language: string
  onHome: () => void
  onToggleFilter: () => void
  onToggleTheme: () => void
  onToggleLanguage: () => void
  onToggleAmbientSound: () => void
  onZoomIn: () => void
  onZoomOut: () => void
  onResetBearing: () => void
}

export function MapControls({
  filterOpen,
  ambientSoundActive,
  theme,
  language,
  onHome,
  onToggleFilter,
  onToggleTheme,
  onToggleLanguage,
  onToggleAmbientSound,
  onZoomIn,
  onZoomOut,
  onResetBearing,
}: MapControlsProps) {
  const label = (key: string) => translate(language, key)

  return (
    <>
      <div className="control-top-left">
        <button
          className="glass-control"
          type="button"
          aria-label={label('controls.home')}
          onClick={onHome}
        >
          <House size={20} />
        </button>
      </div>

      <div className="control-top-right">
        <button
          className={`glass-control ${filterOpen ? 'active' : ''}`}
          type="button"
          aria-label={label('controls.filter')}
          onClick={onToggleFilter}
        >
          <SlidersVertical size={20} />
        </button>
        <button
          className="glass-control"
          type="button"
          aria-label={label(theme === 'dark' ? 'controls.useLight' : 'controls.useDark')}
          onClick={onToggleTheme}
        >
          <Monitor size={20} />
        </button>
        <button
          className="glass-control control-language"
          type="button"
          aria-label={label(language === 'zh' ? 'controls.switchToEnglish' : 'controls.switchToChinese')}
          onClick={onToggleLanguage}
        >
          <Languages size={18} />
          <span aria-hidden="true">{language === 'zh' ? 'EN' : '中'}</span>
        </button>
        <button
          className={`glass-control ${ambientSoundActive ? 'active' : ''}`}
          type="button"
          aria-label={label('controls.ambientSound')}
          onClick={onToggleAmbientSound}
        >
          <Waves size={20} />
        </button>
      </div>

      <div className="control-zoom">
        <button type="button" aria-label={label('controls.zoomIn')} onClick={onZoomIn}>
          <Plus size={21} />
        </button>
        <button type="button" aria-label={label('controls.zoomOut')} onClick={onZoomOut}>
          <Minus size={21} />
        </button>
        <button type="button" aria-label={label('controls.bearing')} onClick={onResetBearing}>
          <Focus size={20} />
        </button>
      </div>
    </>
  )
}
