// frontend/src/components/AmbientSoundPanel.vue
<script setup>
import { computed, watch } from 'vue'
import { CircleAlert, Clock3, Pause, Play, Square, Volume2, Waves, X } from '@lucide/vue'
import { useAmbientSound } from '../composables/useAmbientSound.js'
import { useGlobalAudioPlayer } from '../composables/useGlobalAudioPlayer.js'
import { AmbientSoundConstants } from '../media/ambientSound.constants.js'
import { translate } from '../i18n.js'

const props = defineProps({
  tracks: { type: Array, default: () => [] },
  language: { type: String, default: 'en' },
})

const emit = defineEmits(['close', 'playing-change'])

const trackSource = computed(() => props.tracks)
const {
  mode,
  selectedTrackId,
  selectedMixTrackIds,
  selectedTracks,
  durationMinutes,
  remainingSeconds,
  masterVolume,
  state,
  messageKey,
  isLoading,
  isPlaying,
  isPaused,
  hasValidSelection,
  setMode,
  setSingleTrack,
  toggleMixTrack,
  setDuration,
  setMasterVolume,
  togglePlayback,
  stop,
} = useAmbientSound(trackSource)

const globalAudio = useGlobalAudioPlayer()

globalAudio.registerAmbientHandlers({
  togglePlayback,
  stop,
  pause: () => {
    if (isPlaying.value) togglePlayback()
  },
})

const isMixMode = computed(() => mode.value === AmbientSoundConstants.MODES.MIX)
const mixLimitReached = computed(() => selectedMixTrackIds.value.length >= AmbientSoundConstants.MAX_MIX_TRACK_COUNT)
const durationOptions = AmbientSoundConstants.DURATION_OPTIONS
const secondsPerMinute = AmbientSoundConstants.SECONDS_PER_MINUTE

watch(
  [isPlaying, isPaused, isLoading, remainingSeconds, mode, selectedTracks, durationMinutes, () => props.language],
  () => {
    const totalSec = durationMinutes.value * secondsPerMinute
    const elapsed = Math.max(0, totalSec - remainingSeconds.value)
    const pct = totalSec > 0 ? (elapsed / totalSec) * 100 : 0

    let title = ''
    let subtitle = ''
    const currentTracks = selectedTracks.value || []
    if (mode.value === AmbientSoundConstants.MODES.SINGLE) {
      title = currentTracks[0]?.displayName || currentTracks[0]?.scientificName || translate(props.language, 'floatingPlayer.ambientTitle')
      subtitle = currentTracks[0]?.scientificName || translate(props.language, 'floatingPlayer.ambientSingle')
    } else {
      title = translate(props.language, 'floatingPlayer.ambientTitle')
      subtitle = translate(props.language, 'floatingPlayer.ambientMix', { count: currentTracks.length })
    }

    globalAudio.updateAmbientState({
      isPlaying: isPlaying.value,
      isPaused: isPaused.value,
      isLoading: isLoading.value,
      mode: mode.value,
      title,
      subtitle,
      remainingSeconds: remainingSeconds.value,
      durationMinutes: durationMinutes.value,
      progressPercent: Math.min(100, Math.max(0, pct)),
      trackCount: currentTracks.length,
      thumbnail: currentTracks[0]?.thumbnail || '',
    })
  },
  { immediate: true }
)

const actionLabel = computed(() => {
  if (isLoading.value) return translate(props.language, 'ambient.loading')
  if (isPlaying.value) return translate(props.language, 'ambient.pause')
  if (isPaused.value) return translate(props.language, 'ambient.resume')
  return translate(props.language, 'ambient.play')
})

watch(isPlaying, playing => emit('playing-change', playing), { immediate: true })

function label(key, values) {
  return translate(props.language, key, values)
}

function trackLabel(track) {
  if (!track.scientificName || track.scientificName === track.displayName) return track.displayName
  return `${track.displayName} · ${track.scientificName}`
}

function formatRemainingTime(seconds) {
  const totalSeconds = Math.max(0, Math.round(seconds))
  const minutes = Math.floor(totalSeconds / secondsPerMinute)
  const secondsPart = String(totalSeconds % secondsPerMinute).padStart(2, '0')
  return `${minutes}:${secondsPart}`
}

function onMixTrackChange(trackId) {
  toggleMixTrack(trackId)
}
</script>

<template>
  <aside class="ambient-sound-panel" role="dialog" :aria-label="label('ambient.title')">
    <header class="ambient-sound-panel__header">
      <div>
        <span class="ambient-sound-panel__eyebrow"><Waves :size="14" /> {{ label('ambient.eyebrow') }}</span>
        <h2>{{ label('ambient.title') }}</h2>
        <p>{{ label('ambient.subtitle') }}</p>
      </div>
      <button class="ambient-sound-panel__close" type="button" :aria-label="label('ambient.close')" @click="$emit('close')">
        <X :size="17" />
      </button>
    </header>

    <template v-if="tracks.length">
      <div class="ambient-sound-panel__tabs" role="tablist" :aria-label="label('ambient.mode')">
        <button
          type="button"
          :class="{ 'is-active': !isMixMode }"
          role="tab"
          :aria-selected="!isMixMode"
          @click="setMode(AmbientSoundConstants.MODES.SINGLE)"
        >
          {{ label('ambient.single') }}
        </button>
        <button
          type="button"
          :class="{ 'is-active': isMixMode }"
          role="tab"
          :aria-selected="isMixMode"
          @click="setMode(AmbientSoundConstants.MODES.MIX)"
        >
          {{ label('ambient.mix') }}
        </button>
      </div>

      <section v-if="!isMixMode" class="ambient-sound-panel__section">
        <label class="ambient-sound-panel__field-label" for="ambient-single-track">{{ label('ambient.source') }}</label>
        <select
          id="ambient-single-track"
          :value="selectedTrackId"
          @change="setSingleTrack($event.target.value)"
        >
          <option v-for="track in tracks" :key="track.id" :value="track.id">{{ trackLabel(track) }}</option>
        </select>
      </section>

      <section v-else class="ambient-sound-panel__section">
        <div class="ambient-sound-panel__section-heading">
          <div>
            <span class="ambient-sound-panel__field-label">{{ label('ambient.sources') }}</span>
            <small>{{ label('ambient.selectedCount', { count: selectedMixTrackIds.length }) }}</small>
          </div>
          <span class="ambient-sound-panel__limit">{{ label('ambient.mixMaximum', { count: AmbientSoundConstants.MAX_MIX_TRACK_COUNT }) }}</span>
        </div>
        <div class="ambient-sound-panel__mix-list">
          <label v-for="track in tracks" :key="track.id" class="ambient-sound-panel__track" :class="{ 'is-selected': selectedMixTrackIds.includes(track.id) }">
            <input
              type="checkbox"
              :checked="selectedMixTrackIds.includes(track.id)"
              :disabled="!selectedMixTrackIds.includes(track.id) && mixLimitReached"
              @change="onMixTrackChange(track.id)"
            >
            <span>{{ trackLabel(track) }}</span>
          </label>
        </div>
        <p class="ambient-sound-panel__hint">{{ label('ambient.mixHint') }}</p>
      </section>

      <section class="ambient-sound-panel__section ambient-sound-panel__settings">
        <label class="ambient-sound-panel__field-label" for="ambient-duration">{{ label('ambient.duration') }}</label>
        <select id="ambient-duration" :value="durationMinutes" @change="setDuration(Number($event.target.value))">
          <option v-for="minutes in durationOptions" :key="minutes" :value="minutes">{{ label('ambient.durationOption', { count: minutes }) }}</option>
        </select>

        <div class="ambient-sound-panel__volume">
          <label for="ambient-volume"><Volume2 :size="14" /> {{ label('ambient.volume') }}</label>
          <input
            id="ambient-volume"
            type="range"
            min="0"
            max="1"
            step="0.01"
            :value="masterVolume"
            @input="setMasterVolume(Number($event.target.value))"
          >
        </div>
      </section>

      <div class="ambient-sound-panel__countdown" :class="{ 'is-playing': isPlaying, 'is-paused': isPaused }">
        <Clock3 :size="17" />
        <div>
          <span>{{ label('ambient.remaining') }}</span>
          <strong>{{ formatRemainingTime(remainingSeconds) }}</strong>
        </div>
        <small>{{ label('ambient.loop') }}</small>
      </div>

      <p v-if="messageKey" class="ambient-sound-panel__status" :class="{ 'is-error': state === AmbientSoundConstants.STATES.ERROR }" aria-live="polite">
        <CircleAlert :size="13" />
        <span>{{ label(messageKey, { count: AmbientSoundConstants.MIN_MIX_TRACK_COUNT }) }}</span>
      </p>

      <div class="ambient-sound-panel__actions">
        <button
          class="ambient-sound-panel__play"
          type="button"
          :disabled="isLoading || !hasValidSelection"
          @click="togglePlayback"
        >
          <Pause v-if="isPlaying" :size="16" fill="currentColor" />
          <Play v-else :size="16" fill="currentColor" />
          <span>{{ actionLabel }}</span>
        </button>
        <button class="ambient-sound-panel__stop" type="button" :disabled="isLoading" :aria-label="label('ambient.stop')" @click="stop()">
          <Square :size="15" fill="currentColor" />
          <span>{{ label('ambient.stop') }}</span>
        </button>
      </div>
    </template>

    <p v-else class="ambient-sound-panel__empty"><CircleAlert :size="15" /> {{ label('ambient.unavailable') }}</p>
  </aside>
</template>

// apps/web/src/features/media/AmbientSoundPanel.tsx
import React, { useCallback, useEffect, useRef, useState } from 'react'
import { CircleAlert, Clock3, Pause, Play, Square, Volume2, Waves, X } from 'lucide-react'
import { useAudioPlayer } from './AudioContext.js'
import { resolveAudioForPlayback, audioErrorMessage } from './audioCache.js'
import { translate } from '../../i18n/i18n.js'
import type { AmbientTrack } from '@gbif-globe/contracts'

type State = 'idle' | 'loading' | 'buffering' | 'playing' | 'paused' | 'error'
interface Entry { audio: HTMLAudioElement; url: string; buffering?: boolean }
const EMPTY_TRACKS: AmbientTrack[] = []
const Settings = { DURATIONS: [15, 30, 60, 90], MIN_MIX: 2, MAX_MIX: 4 }
export function AmbientSoundPanel({ tracks = EMPTY_TRACKS, language = 'en', isOpen, loading = false, error, onClose }: {
  tracks?: AmbientTrack[]; language?: string; isOpen: boolean; loading?: boolean; error?: string; onClose: () => void
}) {
  const { registerAmbientHandlers, updateAmbientState } = useAudioPlayer()
  const [mode, setMode] = useState<'single' | 'mix'>('single')
  const [single, setSingle] = useState('')
  const [mix, setMix] = useState<string[]>([])
  const [duration, setDuration] = useState(30)
  const [remaining, setRemaining] = useState(1800)
  const [volume, setVolume] = useState(.62)
  const [state, setState] = useState<State>('idle')
  const [message, setMessage] = useState('')
  const entries = useRef<Entry[]>([])
  const controller = useRef<AbortController | null>(null)
  const generation = useRef(0)
  const deadline = useRef(0)
  const selected = tracks.filter(t => mode === 'single' ? t.id === single : mix.includes(t.id))
  const t = (key: string, args = {}) => translate(language, key, args)
  const release = useCallback((items: Entry[]) => items.forEach(({ audio, url }) => {
    audio.onerror = audio.onwaiting = audio.onstalled = audio.onplaying = null; audio.pause(); audio.removeAttribute('src'); audio.load()
    if (url.startsWith('blob:')) URL.revokeObjectURL(url)
  }), [])
  const stop = useCallback(() => {
    generation.current++; controller.current?.abort(); controller.current = null
    release(entries.current); entries.current = []; deadline.current = 0
    setState('idle'); setMessage(''); setRemaining(duration * 60)
    updateAmbientState({ isPlaying: false, isPaused: false, isLoading: false })
  }, [release, duration, updateAmbientState])
  const pause = useCallback(() => {
    if (state === 'loading' || (state === 'buffering' && !entries.current.length)) {
      generation.current++; controller.current?.abort(); release(entries.current); entries.current = []
      setState('idle'); updateAmbientState({ isPlaying: false, isPaused: false, isLoading: false }); return
    }
    if (state !== 'playing' && state !== 'buffering') return
    entries.current.forEach(e => e.audio.pause()); deadline.current = 0; setState('paused')
  }, [state, release, updateAmbientState])
  const start = useCallback(async () => {
    if (!selected.length || (mode === 'mix' && selected.length < Settings.MIN_MIX)) {
      setMessage(mode === 'mix' ? 'ambient.mixMinimum' : 'ambient.selectionError'); return
    }
    const sequence = ++generation.current
    controller.current?.abort(); controller.current = new AbortController()
    const signal = controller.current.signal
    setState('loading'); setMessage('')
    updateAmbientState({ isLoading: true, isPlaying: false, isPaused: false })
    let prepared: Entry[] = []
    try {
      if ((state === 'paused' || (state === 'error' && message === 'media.autoplayBlocked')) && entries.current.length) prepared = entries.current
      else {
        release(entries.current); entries.current = []
        const results = await Promise.allSettled(selected.map(async track => {
          const resolved = await resolveAudioForPlayback(track.sourceUrl, '/api/audio-proxy', signal, { mediaId: track.id, retry: true })
          const audio = new Audio(resolved.url); audio.loop = true; audio.volume = volume / selected.length
          return { audio, url: resolved.url }
        }))
        prepared = results.flatMap(result => result.status === 'fulfilled' ? [result.value] : [])
        if (!prepared.length) throw (results.find(result => result.status === 'rejected') as PromiseRejectedResult)?.reason || new Error('No audio prepared')
      }
      if (sequence !== generation.current) { release(prepared); return }
      if (!prepared.length) throw new Error('No audio prepared')
      setState('buffering')
      const started = await Promise.allSettled(prepared.map(item => item.audio.play()))
      if (sequence !== generation.current) { release(prepared); return }
      const playable = prepared.filter((_, i) => started[i].status === 'fulfilled')
      const blocked = !playable.length && started.every(result => result.status === 'rejected' && (result.reason as Error)?.name === 'NotAllowedError')
      if (!blocked) release(prepared.filter((_, i) => started[i].status === 'rejected'))
      entries.current = blocked ? prepared : playable
      playable.forEach(item => {
        const refresh = () => { if (sequence === generation.current) setState(entries.current.some(entry => entry.buffering) ? 'buffering' : 'playing') }
        item.audio.onwaiting = item.audio.onstalled = () => { if (!item.audio.paused) { item.buffering = true; refresh() } }
        item.audio.onplaying = () => { item.buffering = false; refresh() }
        item.audio.onerror = () => {
        if (sequence !== generation.current) return
        const errorCode = item.audio.error?.code
        release([item]); entries.current = entries.current.filter(entry => entry !== item)
        if (entries.current.length) setMessage('ambient.partialError')
        else { setState('error'); setMessage(errorCode === 4 ? 'media.unsupportedAudio' : 'media.networkError') }
      } })
      if (!playable.length) throw (started.find(result => result.status === 'rejected') as PromiseRejectedResult)?.reason || new Error('Playback failed')
      if (playable.length !== selected.length) setMessage('ambient.partialError')
      deadline.current = Date.now() + (remaining > 0 ? remaining : duration * 60) * 1000
      setState('playing')
    } catch (reason) {
      if (sequence !== generation.current || signal.aborted) return
      if ((reason as Error)?.name !== 'NotAllowedError') { release(prepared); entries.current = [] }
      setState('error'); setMessage(audioErrorMessage(reason))
    }
  }, [selected.map(t => t.id).join(','), state, mode, volume, remaining, duration, message, release])
  const toggle = useCallback(() => { if (state === 'loading') return; if (state === 'playing' || state === 'buffering') pause(); else void start() }, [state, pause, start])
  useEffect(() => { registerAmbientHandlers({ togglePlayback: toggle, stop, pause }) }, [registerAmbientHandlers, toggle, stop, pause])
  useEffect(() => {
    const ids = new Set(tracks.map(t => t.id))
    setSingle(prev => ids.has(prev) ? prev : tracks[0]?.id || '')
    setMix(prev => {
      const valid = prev.filter(id => ids.has(id))
      if (valid.length >= Settings.MIN_MIX) return valid
      const species = new Set<string>()
      return tracks.filter(t => { const key = t.scientificName || t.id; if (species.has(key)) return false; species.add(key); return true }).slice(0, 3).map(t => t.id)
    })
  }, [tracks])
  useEffect(() => {
    if ((state !== 'playing' && state !== 'buffering') || !deadline.current) return
    const timer = setInterval(() => {
      const next = Math.max(0, Math.ceil((deadline.current - Date.now()) / 1000))
      setRemaining(next)
      if (!next) { stop(); setRemaining(0) }
    }, 1000)
    return () => clearInterval(timer)
  }, [state, stop])
  useEffect(() => { entries.current.forEach(e => { e.audio.volume = volume / Math.max(1, entries.current.length) }) }, [volume])
  useEffect(() => {
    updateAmbientState({ isPlaying: state === 'playing' || state === 'buffering' || state === 'paused', isPaused: state === 'paused', isLoading: state === 'loading',
      status: state === 'loading' ? 'preparing' : state === 'error' ? 'failed' : state,
      errorMessage: state === 'error' ? message : '',
      title: mode === 'single' ? selected[0]?.title || '' : translate(language, 'floatingPlayer.ambientTitle'),
      subtitle: mode === 'single' ? selected[0]?.scientificName || '' : translate(language, 'floatingPlayer.ambientMix', { count: selected.length }),
      mode, durationMinutes: duration, remainingSeconds: remaining })
  }, [state, remaining, duration, mode, single, mix.join(','), language, message, updateAmbientState])
  useEffect(() => () => { generation.current++; controller.current?.abort(); release(entries.current) }, [release])
  if (!isOpen) return null
  const action = state === 'loading' ? 'ambient.loading' : state === 'playing' || state === 'buffering' ? 'ambient.pause' : state === 'paused' ? 'ambient.resume' : state === 'error' ? 'media.retry' : 'ambient.play'
  return <aside className="ambient-sound-panel" role="dialog" aria-label={t('ambient.title')}>
    <header className="ambient-sound-panel__header"><div>
      <span className="ambient-sound-panel__eyebrow"><Waves size={14} /> {t('ambient.eyebrow')}</span>
      <h2>{t('ambient.title')}</h2><p>{t('ambient.subtitle')}</p><a className="audio-queue-link" href="/audio-prewarm">{t('media.queueLink')}</a></div>
      <button className="ambient-sound-panel__close" aria-label={t('ambient.close')} onClick={onClose}><X size={17} /></button>
    </header>
    {loading ? <p role="status" className="ambient-sound-panel__empty">{t('ambient.loading')}</p> : error ? <p role="alert" className="ambient-sound-panel__empty">{error}</p> : !tracks.length ? <p className="ambient-sound-panel__empty">{t('ambient.unavailable')}</p> : <>
      <div className="ambient-sound-panel__tabs" role="tablist" aria-label={t('ambient.mode')}>
        {(['single', 'mix'] as const).map(value => <button key={value} role="tab" aria-selected={mode === value} className={mode === value ? 'is-active' : ''} onClick={() => { stop(); setMode(value) }}>{t(`ambient.${value}`)}</button>)}
      </div>
      <section className="ambient-sound-panel__section">
        {mode === 'single' ? <><label className="ambient-sound-panel__field-label" htmlFor="ambient-single-track">{t('ambient.source')}</label>
          <select id="ambient-single-track" value={single} onChange={e => { stop(); setSingle(e.target.value) }}>{tracks.map(track => <option key={track.id} value={track.id}>{track.title} · {track.scientificName}</option>)}</select></>
          : <><div className="ambient-sound-panel__section-heading"><span>{t('ambient.sources')}</span><small>{t('ambient.selectedCount', { count: mix.length })}</small></div>
            <div className="ambient-sound-panel__mix-list">{tracks.map(track => <label className={`ambient-sound-panel__track ${mix.includes(track.id) ? 'is-selected' : ''}`} key={track.id}>
              <input type="checkbox" checked={mix.includes(track.id)} disabled={!mix.includes(track.id) && mix.length >= Settings.MAX_MIX} onChange={() => { if (mix.includes(track.id) && mix.length <= Settings.MIN_MIX) return; stop(); setMix(mix.includes(track.id) ? mix.filter(id => id !== track.id) : [...mix, track.id]) }} />
              <span>{track.title} · {track.scientificName}</span></label>)}</div><p className="ambient-sound-panel__hint">{t('ambient.mixHint')}</p></>}
      </section>
      <section className="ambient-sound-panel__section ambient-sound-panel__settings">
        <label className="ambient-sound-panel__field-label" htmlFor="ambient-duration">{t('ambient.duration')}</label>
        <select id="ambient-duration" value={duration} onChange={e => { stop(); const next = Number(e.target.value); setDuration(next); setRemaining(next * 60) }}>{Settings.DURATIONS.map(minutes => <option key={minutes} value={minutes}>{t('ambient.durationOption', { count: minutes })}</option>)}</select>
        <div className="ambient-sound-panel__volume"><label htmlFor="ambient-volume"><Volume2 size={14} />{t('ambient.volume')}</label><input id="ambient-volume" type="range" min="0" max="1" step=".01" value={volume} onChange={e => setVolume(Number(e.target.value))} /></div>
      </section>
      <div className={`ambient-sound-panel__countdown ${state === 'playing' ? 'is-playing' : ''}`}><Clock3 size={17} /><div><span>{t('ambient.remaining')}</span><strong>{Math.floor(remaining / 60)}:{String(remaining % 60).padStart(2, '0')}</strong></div><small>{t('ambient.loop')}</small></div>
      {message && <p className={`ambient-sound-panel__status ${state === 'error' ? 'is-error' : ''}`} role="status"><CircleAlert size={13} />{t(message, { count: Settings.MIN_MIX })}</p>}
      <div className="ambient-sound-panel__actions"><button className="ambient-sound-panel__play" disabled={state === 'loading' || !selected.length} onClick={toggle}>{state === 'playing' || state === 'buffering' ? <Pause size={16} /> : <Play size={16} />}{t(action)}</button>
        <button className="ambient-sound-panel__stop" aria-label={t('ambient.stop')} onClick={stop}><Square size={15} />{t('ambient.stop')}</button></div>
    </>}
  </aside>
}
